"""Unity 适配器：借助 BepInEx + XUnity.AutoTranslator 做显示层替换。

不改游戏资源与程序集；生成 XUnity 的静态译文表，显示时由插件把原文换成译文，
游戏内部仍是原文，所以 dual 用途可以放行。禁用 XUnity 的在线/机器翻译端点。

候选来源：
  1. XUnity 运行时捕获的文本（_AutoGeneratedTranslations.txt 等的键；丢弃其中的机翻值）——确定显示过；
  2. UnityPy 静态扫描 TextAsset 行与 MonoBehaviour 序列化字符串——需用途审核。
"""
from pathlib import Path
import configparser
import re
import shutil
import subprocess
import time

from . import register
from .base import Adapter, Occurrence, copy_tree
from .. import saveguard
from ..textutil import is_candidate

OUR_FILE = 'glk_translations.txt'


def escape(text):
    out = text.replace('\\', '\\\\').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t').replace('=', '\\=')
    return '\\' + out if out.startswith('//') else out


def unescape(text):
    result, i = [], 0
    while i < len(text):
        ch = text[i]
        if ch == '\\' and i + 1 < len(text):
            nxt = text[i + 1]
            result.append({'n': '\n', 'r': '\r', 't': '\t'}.get(nxt, nxt))
            i += 2
        else:
            result.append(ch)
            i += 1
    return ''.join(result)


def split_line(line):
    """按第一个未转义的 = 拆分 XUnity 译文行。"""
    i = 0
    while i < len(line):
        if line[i] == '\\':
            i += 2
            continue
        if line[i] == '=':
            return line[:i], line[i + 1:]
        i += 1
    return None


def backend(game):
    data = next(iter(game.glob('*_Data')), None)
    if data is None:
        return None
    if (game / 'GameAssembly.dll').exists():
        return 'il2cpp'
    if (data / 'Managed' / 'Assembly-CSharp.dll').exists():
        return 'mono'
    return 'unknown'


def bepinex_flavor(root):
    core = Path(root) / 'BepInEx' / 'core'
    if not core.exists():
        return None
    if any(core.glob('BepInEx.Unity.IL2CPP.dll')) or any(core.glob('BepInEx.IL2CPP.dll')):
        return 'il2cpp'
    return 'mono'


def _unity_strings(raw, lang, minimum=2):
    """Unity 序列化：int32 长度 + UTF-8 + 4 字节对齐。"""
    pos = 0
    while pos + 4 <= len(raw):
        length = int.from_bytes(raw[pos:pos + 4], 'little')
        if minimum <= length <= 8192 and pos + 4 + length <= len(raw):
            try:
                text = bytes(raw[pos + 4:pos + 4 + length]).decode('utf-8')
            except UnicodeDecodeError:
                text = None
            if text and is_candidate(text, lang):
                yield text
                pos += 4 + (length + 3) // 4 * 4
                continue
        pos += 4


@register
class UnityAdapter(Adapter):
    name = 'unity'
    title = 'Unity（Mono / IL2CPP，经 BepInEx + XUnity.AutoTranslator 显示层替换）'
    display_layer = True
    token_patterns = (r'</?[A-Za-z][^<>\n]*>',)
    personal_data_globs = ('*.log', 'BepInEx/cache/*', 'BepInEx/LogOutput.log')
    translator_notes = ('- Unity 富文本标签（<color=#fff>…</color>、<b>、<size=30>、<sprite=…> 等）原样保留，只翻译标签外的文字。\n'
                        '- 译文中不要出现单独一行以 // 开头的文字。')

    @classmethod
    def detect(cls, game_dir):
        game_dir = Path(game_dir)
        return 90 if (game_dir / 'UnityPlayer.dll').exists() and any(game_dir.glob('*_Data')) else 0

    def data_dir(self):
        found = next(iter(self.game.glob('*_Data')), None)
        if found is None:
            raise FileNotFoundError('找不到 *_Data 目录')
        return found

    def runtime_dir(self):
        """BepInEx + XUnity 来源：配置的 runtime_dir，或游戏自身已安装的。"""
        configured = self.options.get('runtime_dir')
        if configured:
            return Path(configured)
        if (self.game / 'BepInEx' / 'plugins' / 'XUnity.AutoTranslator').exists() or any((self.game / 'BepInEx' / 'plugins').rglob('XUnity.AutoTranslator.Plugin.Core.dll')):
            return self.game
        return None

    # ---- 提取 ----
    def captured_files(self):
        files = list(self.options.get('captured_files', []))
        text_dir = self.game / 'BepInEx' / 'Translation'
        if text_dir.exists():
            files += [str(p) for p in text_dir.rglob('*.txt') if p.name != OUR_FILE]
        return [Path(f) for f in files]

    def extract(self):
        lang = self.ws.source_lang
        for path in self.captured_files():
            for n, line in enumerate(path.read_text(encoding='utf-8-sig', errors='replace').splitlines(), 1):
                if not line.strip() or line.startswith('//') or line.startswith(('r:', 'sr:')):
                    continue
                parts = split_line(line)
                if parts:
                    source = unescape(parts[0])
                    if is_candidate(source, lang):
                        yield Occurrence(source, 'runtime-captured', f'{path.name}:{n}', '', 'display')
        if self.options.get('static_scan', True):
            yield from self._static(lang)

    def _static(self, lang):
        try:
            import UnityPy
        except ImportError:
            yield Occurrence('<未安装 UnityPy，跳过静态扫描>', 'error', '', '', 'excluded')
            return
        env = UnityPy.load(str(self.data_dir()))
        for obj in env.objects:
            kind = obj.type.name
            if kind == 'TextAsset':
                data = obj.read()
                script = getattr(data, 'm_Script', '')
                if isinstance(script, bytes):
                    try:
                        script = script.decode('utf-8-sig')
                    except UnicodeDecodeError:
                        continue
                name = getattr(data, 'm_Name', '') or getattr(data, 'name', '')
                for n, line in enumerate(script.splitlines(), 1):
                    if is_candidate(line, lang) and len(line) < 2000:
                        yield Occurrence(line.strip(), 'asset:TextAsset', f'{name}:{n}', 'TextAsset 行（格式依游戏而定，整行可能含数据字段）')
            elif kind == 'MonoBehaviour':
                try:
                    raw = obj.get_raw_data()
                except Exception:  # noqa: BLE001 — 个别对象读取失败不影响整体
                    continue
                for text in _unity_strings(raw, lang):
                    yield Occurrence(text, 'asset:MonoBehaviour', f'path_id={obj.path_id}', '')

    # ---- 构建 ----
    def build(self, mapping, out_dir):
        out_dir = Path(out_dir)
        runtime = self.runtime_dir()
        if runtime is None:
            raise ValueError('游戏未安装 BepInEx + XUnity.AutoTranslator；请在 glk.json 的 adapter.runtime_dir 指向一个已装好的同类型（Mono/IL2CPP）游戏或插件包目录')
        flavor, need = bepinex_flavor(runtime), backend(self.game)
        if flavor and need in ('mono', 'il2cpp') and flavor != need:
            raise ValueError(f'BepInEx 类型不匹配：游戏是 {need}，runtime_dir 是 {flavor}')
        copy_tree(self.game, out_dir, exclude=(*self.personal_data_globs, 'BepInEx/Translation/*'))
        if runtime != self.game:
            for rel in ('BepInEx', 'winhttp.dll', 'doorstop_config.ini', '.doorstop_version'):
                src = runtime / rel
                if src.is_dir():
                    for path in src.rglob('*'):
                        relp = path.relative_to(runtime).as_posix()
                        if path.is_file() and not relp.startswith(('BepInEx/Translation/', 'BepInEx/cache/', 'BepInEx/config/')) and not relp.endswith('.log'):
                            dest = out_dir / relp
                            dest.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copy2(path, dest)
                elif src.is_file():
                    shutil.copy2(src, out_dir / rel)
            for font in runtime.glob('arialuni_sdf*'):
                shutil.copy2(font, out_dir / font.name)
        lang = self.options.get('xunity_language', 'zh')
        text_dir = out_dir / 'BepInEx' / 'Translation' / lang / 'Text'
        text_dir.mkdir(parents=True, exist_ok=True)
        lines = [f'{escape(s)}={escape(t)}' for s, t in sorted(mapping.items()) if t != s]
        (text_dir / OUR_FILE).write_text('\n'.join(lines) + '\n', encoding='utf-8')
        self._configure(out_dir, runtime, lang)
        return {'entries': len(lines), 'bepinex': flavor or 'game-installed', 'translation_file': (text_dir / OUR_FILE).relative_to(out_dir).as_posix()}

    def _configure(self, out_dir, runtime, lang):
        """复制并改写 XUnity 配置：关闭在线翻译端点，只用静态译文。"""
        cfg_dir = out_dir / 'BepInEx' / 'config'
        cfg_dir.mkdir(parents=True, exist_ok=True)
        src = runtime / 'BepInEx' / 'config' / 'AutoTranslatorConfig.ini'
        parser = configparser.RawConfigParser(strict=False)
        parser.optionxform = str
        if src.exists():
            parser.read(src, encoding='utf-8-sig')
        for section in ('Service', 'General', 'Files', 'Behaviour'):
            if not parser.has_section(section):
                parser.add_section(section)
        parser.set('Service', 'Endpoint', '')
        parser.set('Service', 'FallbackEndpoint', '')
        parser.set('General', 'Language', lang)
        parser.set('General', 'FromLanguage', self.ws.source_lang)
        parser.set('Files', 'Directory', r'Translation\{Lang}\Text')
        parser.set('Files', 'OutputFile', r'Translation\{Lang}\Text\_AutoGeneratedTranslations.txt')
        for key, value in self.options.get('xunity_overrides', {}).items():
            section, _, name = key.partition('.')
            if not parser.has_section(section):
                parser.add_section(section)
            parser.set(section, name, str(value))
        with (cfg_dir / 'AutoTranslatorConfig.ini').open('w', encoding='utf-8') as f:
            parser.write(f, space_around_delimiters=False)

    def launcher(self, out_dir):
        exes = [p for p in Path(out_dir).glob('*.exe') if 'crashhandler' not in p.name.lower()]
        return exes[0].name if exes else None

    def shared_save_locations(self, out_dir):
        """PlayerPrefs 在 HKCU\Software\公司\产品，存档常在 LocalLow\公司\产品。"""
        info = next(iter(Path(out_dir).glob('*_Data/app.info')), None)
        lines = info.read_text(encoding='utf-8', errors='replace').splitlines() if info else []
        if len(lines) < 2 or not lines[0].strip() or not lines[1].strip():
            raise RuntimeError('读不到 *_Data/app.info 的公司/产品名，无法定位共用存档，拒绝自动启动')
        company, product = lines[0].strip(), lines[1].strip()
        return [('reg', f'HKCU\Software\{company}\{product}'), ('dir', saveguard.locallow(company, product))]

    def probe(self, out_dir, seconds=40):
        exe = self.launcher(out_dir)
        if not exe:
            return {'skipped': '找不到 EXE'}
        log = Path(out_dir) / 'BepInEx' / 'LogOutput.log'
        child = subprocess.Popen([str(Path(out_dir) / exe)], cwd=out_dir)
        deadline = time.time() + seconds
        text = ''
        while time.time() < deadline and child.poll() is None:
            time.sleep(2)
            if log.exists():
                text = log.read_text(encoding='utf-8', errors='replace')
                if re.search(r'XUnity\.AutoTranslator.*(Loaded|loaded)', text) and time.time() > deadline - seconds + 15:
                    break
        alive = child.poll() is None
        if alive:
            subprocess.run(['taskkill', '/PID', str(child.pid), '/T', '/F'], capture_output=True)
        errors = [ln for ln in text.splitlines() if 'AutoTranslator' in ln and ('Error' in ln or 'Exception' in ln)]
        loaded = [ln for ln in text.splitlines() if 'AutoTranslator' in ln and 'oaded' in ln]
        return {'ok': alive and bool(loaded) and not errors, 'alive': alive, 'loaded_lines': loaded[:3], 'errors': errors[:5]}
