"""各文件格式的读写：只改动目标字符串，其余字节/结构保持不变。"""
import json
import struct

import pytest

from gamelockit.adapters.wolf import WolfAdapter
from gamelockit.formats import asar, kag, tjs, wolf, xp3


def test_xp3_roundtrip(tmp_path):
    files = {'scenario/first.ks': 'テスト\n'.encode('utf-16le'), 'system/Config.tjs': b'x=1;'}
    xp3.write(tmp_path / 'patch.xp3', files)
    assert xp3.read(tmp_path / 'patch.xp3') == files
    assert set(xp3.read(tmp_path / 'patch.xp3', lambda n: n.endswith('.ks'))) == {'scenario/first.ks'}


def test_tjs_literals_skip_comments_and_reject_unsafe_target():
    src = 'var a = "はい"; // "コメント"\n/* "ブロック" */ var b = \'いいえ\';'
    assert [c for *_, c in tjs.string_literals(src)] == ['はい', 'いいえ']
    out, n = tjs.apply_literals(src, {'はい': '是', 'コメント': '注释'})
    assert n == 1 and '"是"' in out and '"コメント"' in out
    with pytest.raises(ValueError):
        tjs.apply_literals(src, {'はい': '他说"是"'})


def test_kag_units_skip_script_blocks_and_replace_in_place():
    src = '*start\n#太郎\nこんにちは[l][r]\n[iscript]\nf.x = "内部";\n[endscript]\n[link text="次へ"]\n'
    units = [(kind, text) for _, kind, _, _, text in kag.scenario_units(src)]
    assert units == [('speaker', '太郎'), ('text', 'こんにちは[l][r]'), ('attr:text', '次へ')]
    out, n = kag.apply_units(src, {'こんにちは[l][r]': '你好[l][r]', '次へ': '下一步', '内部': '×'})
    assert n == 2 and '你好[l][r]' in out and 'text="下一步"' in out and '"内部"' in out


def _asar(files):
    header = {'files': {name: {'offset': '0', 'size': 0} for name in files}}
    raw = json.dumps(header).encode()
    padded = raw + bytes((-len(raw)) % 4)
    pickle = struct.pack('<II', len(padded) + 4, len(raw)) + padded
    empty = struct.pack('<II', 4, len(pickle)) + pickle
    return asar.rewrite(empty, files)


def test_asar_rewrite_keeps_other_files():
    data = _asar({'a.js': b'alert(1)', 'b.ks': 'はい'.encode()})
    new = asar.rewrite(data, {'b.ks': '是的'.encode()})
    assert asar.read(new) == {'a.js': b'alert(1)', 'b.ks': '是的'.encode()}
    with pytest.raises(ValueError):
        asar.rewrite(data, {'missing.js': b''})


def _wstr(text, enc='utf-8'):
    raw = text.encode(enc) + b'\x00'
    return struct.pack('<i', len(raw)) + raw


def _game_dat(unicode=True):
    magic = bytearray(wolf.DAT_MAGIC)
    if unicode:
        magic[9] = ord('U')
    body = bytes(magic) + struct.pack('<i', 2) + b'\x01\x02' + struct.pack('<i', 9)
    for i, text in enumerate(['タイトル', 'x', 'KEY', 'a', 'MS Gothic', 'b', 'c', 'd', 'Ver1.0 説明']):
        body += struct.pack('<i', 3) + b'\xff\xfe\x01' if i == 2 else _wstr(text)
    body += b'\x00\x00\x00\x00tail'
    return bytearray(body)


def test_wolf_game_dat_rebuild_updates_strings_and_size_field():
    data = _game_dat()
    size_at = len(data) - 8
    data[size_at:size_at + 4] = struct.pack('<i', len(data) - 1)
    data = bytes(data)
    spans, found_size_at = wolf.parse_game_dat(data)
    assert found_size_at == size_at
    assert wolf.encoding_of(data, 'game') == 'utf-8'
    kinds = {s.kind for s in spans}
    assert {'title', 'font', 'version'} <= kinds
    assert wolf.rebuild(data, spans, {}, 'utf-8', size_at) == data
    version = next(i for i, s in enumerate(spans) if s.kind == 'version')
    new = wolf.rebuild(data, spans, {version: '1.0 版 中文说明'}, 'utf-8', size_at)
    spans2, at2 = wolf.parse_game_dat(new)
    assert spans2[version].raw.decode() == '1.0 版 中文说明'
    assert struct.unpack_from('<i', new, at2)[0] == len(new) - 1
    assert new.endswith(b'tail')


def test_wolf_adapter_guards_encoding():
    with pytest.raises(ValueError, match='Unicode'):
        WolfAdapter.check_writable(None, 'cp932')
    WolfAdapter.check_writable(None, 'utf-8')
    span = wolf.Span(0, 3, b'\xeb\x00', 'x', 'message')
    with pytest.raises(ValueError, match='source_encoding'):
        WolfAdapter.texts('a.dat', {'encoding': 'cp932', 'spans': [span]})


def test_unity_captured_file_bom_not_part_of_key(tmp_path):
    from types import SimpleNamespace
    from gamelockit.adapters.unity import UnityAdapter
    text_dir = tmp_path / 'BepInEx' / 'Translation' / 'zh' / 'Text'
    text_dir.mkdir(parents=True)
    (text_dir / '_AutoGeneratedTranslations.txt').write_bytes('\ufeffはじめる\\r=x\r\nつづき=y\r\n'.encode('utf-8'))
    ws = SimpleNamespace(game_dir=tmp_path, config={'adapter': {'static_scan': False}}, source_lang='ja')
    sources = [o.source for o in UnityAdapter(ws).extract()]
    assert sources == ['はじめる\r', 'つづき']
